### ISSUE TITLE
Non-unique Key Issue

### ISSUE THREAD

**Issue by zbarnz** [SocexSolutions/agenda-v2#207]
If you add chip components that use key props in a patter of one non-unique then at least one unique then one non-unique (ex: [topic1, topic2, topic1]. Then when you try to delete the first topic in the array the chip will not delete and in some cases will add back other deleted array elements. 

I tried to find the cause for a while and couldn't figure it out. Since we delete chips by their index and not their key I dont see why this is a problem.

EDIT: after further testing any subsequent chip additions will duplicate the non-unique chip and the non-unique chip will always appear first in the array. This also only occurs if you first try to delete the first non-unique chip in the array before deleting any other chip.

Live example:

![chrome-capture (1)](https://user-images.githubusercontent.com/80174782/163770881-e3b62d37-f3ff-4029-a07e-484f7f60696a.gif)

**Comment by thudsonbu** [comment]
This is happening because React uses the `key` prop to decide what has changed in an array. We don't have unique `key` elements in this case so I will just make it so that you can't create new Topic's with the same name.

**Comment by thudsonbu** [comment]
Fix inbound: https://github.com/SocexSolutions/agenda-v2/pull/208

**Comment by thudsonbu** [comment]
I am not sure but there might still be an issue with this. It also might have just been the older topics I had added. LMK if it seems to come up again.
