### ISSUE TITLE
Date decoding issue in JWT

### ISSUE THREAD

**Issue by zbarnz** [SocexSolutions/agenda-v2#209]
When we decode the expiration date sent to our JWT handler it decodes it as only a few seconds after the current time. Even if the date set on the cookie is 24 hours in the future. We will need to fix this before pushing the change to use owner_id from our authentication middleware.

This seems like a new issue

**Comment by thudsonbu** [comment]
I think I already pushed the fix for this, the `jsonwebtoken` lib docs are wrong so I switched to adding our own date.
