### ISSUE TITLE
api/lib/utils/autoPopulate.js 

### ISSUE THREAD

**Issue by Dahvd** [SocexSolutions/agenda-v2#45]
When I run the file it only adds users.  The meetings are not added.

![image](https://user-images.githubusercontent.com/23304775/136124090-4eea9be8-2e3b-41d5-a631-a088ac3af09f.png)

**Comment by thudsonbu** [comment]
The output there only represents the result from `users.find({})` which doesn't include meetings. Can you confirm that there are no other records in rob3t or using the mongodb cli?

**Comment by thudsonbu** [comment]
This version of the script is deprecated @zbarnz @Dahvd.
